name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          # Windows Server 2016 + Visual Studio 2017
          - name: "Windows Server 2016 + Visual Studio 2017"
            os: windows-2016
          # Windows Server 2019 + Visual Studio 2019
          - name: "Windows Server 2019 + Visual Studio 2019"
            os: windows-2019

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure Build
      run: mkdir build && cd build && cmake ..
    - name: Build
      run: cd build && cmake --build .
    - name: Run Unit Test
      run: /a/doctest/doctest/build/Debug/main.exe